apiVersion: apps/v1
kind: Deployment
metadata:
  name: TicketDelivery
  labels:
    app: TicketDelivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TicketDelivery
  template:
    metadata:
      labels:
        app: TicketDelivery
    spec:
      containers:
        - name: TicketDelivery
          image: username/TicketDelivery:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5